package initcmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// integrationTables turns the uv-generated project into the private root
// integration workspace required by the architecture.
const integrationTables = `
[tool.uv]
package = false

[tool.uv.workspace]
members = []
exclude = [".worktrees/**"]
`

// makeIntegrationWorkspace appends the integration tables to the pyproject.toml
// generated by "uv init --bare", preserving its content verbatim.
//
// It is not a TOML editor. Unrelated [tool.*] tables are kept as they are, but
// any definition in the tool.uv namespace that za writes is refused rather than
// duplicated or overwritten.
func makeIntegrationWorkspace(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read uv-generated pyproject.toml: %w", err)
	}
	content := string(data)

	hasProject, err := checkUVNamespace(content)
	if err != nil {
		return err
	}
	if !hasProject {
		return fmt.Errorf("uv-generated pyproject.toml has no [project] table")
	}

	content = strings.TrimRight(content, "\r\n") + "\n" + integrationTables
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write pyproject.toml: %w", err)
	}
	return nil
}

// checkUVNamespace scans the table headers and keys of content, reports
// whether it has a [project] table, and fails if anything already defines the
// tool.uv namespace. It is a line scanner sized for freshly generated uv
// output, not a general TOML parser: content inside multi-line strings is not
// recognized, which can only produce a spurious refusal.
func checkUVNamespace(content string) (hasProject bool, err error) {
	var table []string // key path of the current table; nil at the root
	sc := bufio.NewScanner(strings.NewReader(content))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if header, ok := parseHeader(line); ok {
			table = splitKey(header)
			if len(table) == 1 && table[0] == "project" {
				hasProject = true
			}
			if isUVOwned(table) {
				return false, conflict("[" + header + "]")
			}
			continue
		}
		raw, _, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key := append(append([]string(nil), table...), splitKey(raw)...)
		// A root-level "tool" key is an inline table that [tool.uv] cannot extend.
		if isUVOwned(key) || (table == nil && len(key) == 1 && key[0] == "tool") {
			return false, conflict(fmt.Sprintf("key %q in %s", strings.TrimSpace(raw), tableName(table)))
		}
	}
	if err := sc.Err(); err != nil {
		return false, fmt.Errorf("read uv-generated pyproject.toml: %w", err)
	}
	return hasProject, nil
}

func conflict(what string) error {
	return fmt.Errorf("uv-generated pyproject.toml unexpectedly defines %s in the uv configuration za owns; refusing to overwrite it", what)
}

// isUVOwned reports whether key path p lies in the tool.uv namespace.
func isUVOwned(p []string) bool {
	return len(p) >= 2 && p[0] == "tool" && p[1] == "uv"
}

func tableName(table []string) string {
	if table == nil {
		return "the root table"
	}
	return "[" + strings.Join(table, ".") + "]"
}

// parseHeader returns the key of a [table] or [[array]] header line. Lines
// that only start with a bracket, such as array elements, are not headers.
func parseHeader(line string) (string, bool) {
	open, close := "[", "]"
	if strings.HasPrefix(line, "[[") {
		open, close = "[[", "]]"
	} else if !strings.HasPrefix(line, "[") {
		return "", false
	}
	key, rest, ok := strings.Cut(line[len(open):], close)
	rest = strings.TrimSpace(rest)
	if !ok || strings.TrimSpace(key) == "" || (rest != "" && !strings.HasPrefix(rest, "#")) {
		return "", false
	}
	return strings.TrimSpace(key), true
}

// splitKey splits a dotted TOML key into its parts, removing surrounding
// whitespace and the quotes of quoted parts.
func splitKey(key string) []string {
	var parts []string
	var b strings.Builder
	var quote rune
	for _, r := range key {
		switch {
		case quote != 0:
			if r == quote {
				quote = 0
			} else {
				b.WriteRune(r)
			}
		case r == '"' || r == '\'':
			quote = r
		case r == '.':
			parts = append(parts, strings.TrimSpace(b.String()))
			b.Reset()
		default:
			b.WriteRune(r)
		}
	}
	return append(parts, strings.TrimSpace(b.String()))
}
