package initcmd

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

// integrationTables turns the uv-generated project into the private root
// integration workspace required by the architecture.
const integrationTables = `
[tool.uv]
package = false

[tool.uv.workspace]
members = []
exclude = [".worktrees/**"]
`

// makeIntegrationWorkspace appends the integration tables to the pyproject.toml
// generated by "uv init --bare", preserving its [project] metadata verbatim.
//
// It is not a TOML editor: it refuses any file that already declares [tool]
// tables, since appending could then produce duplicate tables.
func makeIntegrationWorkspace(path string) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read uv-generated pyproject.toml: %w", err)
	}
	content := string(data)

	hasProject := false
	sc := bufio.NewScanner(strings.NewReader(content))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		switch {
		case line == "[project]":
			hasProject = true
		case strings.HasPrefix(line, "[tool") || strings.HasPrefix(line, "[[tool"):
			return fmt.Errorf("uv-generated pyproject.toml unexpectedly contains %s; refusing to edit it", line)
		}
	}
	if err := sc.Err(); err != nil {
		return fmt.Errorf("read uv-generated pyproject.toml: %w", err)
	}
	if !hasProject {
		return fmt.Errorf("uv-generated pyproject.toml has no [project] table")
	}

	content = strings.TrimRight(content, "\r\n") + "\n" + integrationTables
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write pyproject.toml: %w", err)
	}
	return nil
}
